db_file:
  internal/testing/database.json

source_url:
  https://xkcd.com

parallel:
  24

cache_file:
  cache.json

client_log_file:
  "logs/xkcd/bad_request.log"

index_file:
  internal/testing/index.json